name: say-hello
on: push 
jobs:
  say-hello-job:
     runs-on: ubuntu-latest
     steps:
       - name: access repo code
         uses: actions/checkout@v4.1.5
       - run: echo "$(cat hello_world.txt)"
