name: hello-here
on: push
jobs:
  say-hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: read repo codes
        uses: actions/checkout@v4.1.5
      - run: echo "$(cat hello_world.txt)"
      - name: set node version
        uses: actions/setup-node@v4.0.2
        with:
          node-vesrion: '18.x'
      - run: npm install
      - run: npm run build 
